#!/bin/bash -e
#

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"

USAGE=$(cat <<EOF
$0 [options]
    --publish             Build and publish Gluecodium locally and use it for code generation
    --buildGluecodium         Build and use local Gluecodium version
    --gluecodiumPath [PATH]   Implies --buildGluecodium, path to local gluecodium (default: ${GLUECODIUM_PATH})
    --debug               Build with debug symbols
    --asan                Run with AddressSanitizer
    --help                Print this message
EOF
)

BUILD_LOCAL_GLUECODIUM=false
CMAKE_EXTRA_PARAMETERS=

while [[ $# -gt 0 ]]; do
    case "$1" in
        --publish)
            publish_local
            shift
            ;;
        --buildGluecodium)
            BUILD_LOCAL_GLUECODIUM=true
            shift
            ;;
        --gluecodiumPath)
            BUILD_LOCAL_GLUECODIUM=true
            GLUECODIUM_PATH="$2"
            shift 2
            ;;
        --debug)
            CMAKE_EXTRA_PARAMETERS="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
            shift
            ;;
        --asan)
            CMAKE_EXTRA_PARAMETERS="${CMAKE_EXTRA_PARAMETERS} -DBUILD_DART_WITH_ASAN=ON"
            shift
            ;;
        --help|*)
            echo "$USAGE"
            exit 0
            ;;
    esac
done

if [[ "$BUILD_LOCAL_GLUECODIUM" = "true" ]]; then
    export GLUECODIUM_PATH
fi

GLUECODIUM_VERSION="${GLUECODIUM_VERSION:-+}"
BUILD_DIR=${PWD}/build-dart
INSTALL_DIR=${PWD}/dist/dart

[ -d "${BUILD_DIR}" ] || mkdir -p "${BUILD_DIR}"
[ -d "${INSTALL_DIR}" ] || mkdir -p "${INSTALL_DIR}"

set -x
CWD=${PWD}
pushd "${BUILD_DIR}"

tmppipe=$(mktemp -u)
mkfifo -m 600 "$tmppipe"
trap 'rm -rf "$tmppipe"' EXIT HUP INT TERM
tee cmake_output.log < "$tmppipe" &
safe cmake \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_C_COMPILER="$(which clang)" \
    -DCMAKE_CXX_COMPILER="$(which clang++)" \
    -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DFUNCTIONAL_GLUECODIUM_GENERATOR=dart \
    -DFUNCTIONAL_GLUECODIUM_VERSION="${GLUECODIUM_VERSION}" \
    -DFUNCTIONAL_BUILD_DART_TESTS=ON \
    -G Ninja \
    ${CMAKE_EXTRA_PARAMETERS} \
    .. > "$tmppipe"
popd

safe cmake --build "${BUILD_DIR}"

pushd "${BUILD_DIR}"
ctest --verbose
popd
