#!/bin/bash -e
#
# Copyright (C) 2016-2018 HERE Europe B.V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE


SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"

USAGE=$(cat <<EOF
$0 [options]
    --publish                 Build and publish Gluecodium locally and use it for code generation
    --buildGluecodium         Build and use local Gluecodium version
    --gluecodiumPath [PATH]   Implies --buildGluecodium, path to local gluecodium (default: ${GLUECODIUM_PATH})
    --debug                   Build with debug symbols
    --docs                    Generate Javadoc of SDK
    --jemalloc                Run tests with jemalloc
    --hostOnly                Only build host architecture
    --help                    Print this message
EOF
)

CMAKE_BUILD_TYPE=
BUILD_LOCAL_GLUECODIUM=false
GENERATE_DOCS=false
HOST_ONLY=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --publish)
            publish_local
            shift
            ;;
        --buildGluecodium)
            BUILD_LOCAL_GLUECODIUM=true
            shift
            ;;
        --gluecodiumPath)
            BUILD_LOCAL_GLUECODIUM=true
            GLUECODIUM_PATH="$2"
            shift 2
            ;;
        --jemalloc)
            USE_JEMALLOC=true
            shift
            ;;
        --debug)
            CMAKE_BUILD_TYPE="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
            shift
            ;;
        --docs)
            GENERATE_DOCS=true
            shift
            ;;
        --hostOnly)
            HOST_ONLY=true
            shift
            ;;
        --help|*)
            echo "$USAGE"
            exit 0
            ;;
    esac
done

if [[ "$BUILD_LOCAL_GLUECODIUM" = "true" ]]; then
    export GLUECODIUM_PATH
fi

# Sanity checks
[ $ANDROID_HOME ] || die "ANDROID_HOME environment variable is mandatory"

if [ "$USE_JEMALLOC" = true ]; then
    command -v jemalloc-config >/dev/null || die "jemalloc is required for this option"
    JEMALLOC_LIB=$(jemalloc-config --libdir)/libjemalloc.so.$(jemalloc-config --revision)
    CMAKE_BUILD_TYPE="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
fi

GLUECODIUM_VERSION="${GLUECODIUM_VERSION:-+}"
BUILD_DIR_PREFIX="${PWD}/build-android-"
ANDROID_DIR="${PWD}/functional/android"
DIST_ANDROID_DIR="${PWD}/dist/android"
DOCS_DIR="${DIST_ANDROID_DIR}/docs"
INSTALL_AAR_DIR="${ANDROID_DIR}/app/libs/"
TMP_DIR=$(mktemp -d)

if $HOST_ONLY; then
    ./gradlew functional:testRelease -PhostOnly -PgluecodiumVersion=${GLUECODIUM_VERSION}
else
    ./gradlew functional:testRelease -PgluecodiumVersion=${GLUECODIUM_VERSION}
fi

if [ "$GENERATE_DOCS" = true ]; then
    ./gradlew generateJavadoc
fi
