excludes:
  scopes:
  - name: "test.*"
    reason: "TEST_TOOL_OF"
    comment: "These are dependencies used for testing. They are not distributed in the context of this project."
  - name: ".*Test.*"
    reason: "TEST_TOOL_OF"
    comment: "These are dependencies used for testing. They are not distributed in the context of this project."
