/*
 * Copyright (C) 2016-2026 HERE Europe B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

package com.here.gluecodium.generator.typescript

import com.here.gluecodium.generator.common.GeneratedFile
import com.here.gluecodium.generator.common.TurboModuleCallableNameResolver
import com.here.gluecodium.generator.common.makeFullFields
import com.here.gluecodium.generator.common.orderedByPrimaryThenArity
import com.here.gluecodium.generator.common.orderedFieldCtorsByPrimaryThenArity
import com.here.gluecodium.model.lime.LimeAttributeType
import com.here.gluecodium.model.lime.LimeAttributeValueType
import com.here.gluecodium.model.lime.LimeBasicType
import com.here.gluecodium.model.lime.LimeClass
import com.here.gluecodium.model.lime.LimeEnumeration
import com.here.gluecodium.model.lime.LimeFunction
import com.here.gluecodium.model.lime.LimeInterface
import com.here.gluecodium.model.lime.LimeLambda
import com.here.gluecodium.model.lime.LimeList
import com.here.gluecodium.model.lime.LimeMap
import com.here.gluecodium.model.lime.LimeParameter
import com.here.gluecodium.model.lime.LimeStruct
import com.here.gluecodium.model.lime.LimeType
import com.here.gluecodium.model.lime.LimeTypeRef

/**
 * Generates idiomatic TypeScript wrapper classes on top of handle-based TurboModule specs.
 */
internal class TypeScriptWrapperEmitter(
    private val nameResolver: TypeScriptNameResolver,
    libraryName: String = "library",
) {
    private val baseName = libraryName.split("_", "-").joinToString("") { it.replaceFirstChar { c -> c.uppercase() } }
    private val baseClassName = "${baseName}Base"
    private val errorClassName = "${baseName}Error"
    private val baseFileName = "_$baseClassName"

    private val generatedNames = mutableListOf<String>()
    private val structNames = mutableSetOf<String>()
    private val classNames = mutableSetOf<String>()
    private val enumNames = mutableSetOf<String>()

    fun generate(
        classes: List<LimeClass>,
        structs: List<LimeStruct>,
        enums: List<LimeEnumeration>,
    ): List<GeneratedFile> {
        val files = mutableListOf<GeneratedFile>()

        for (e in enums) {
            enumNames += nameResolver.resolveName(e)
        }
        for (s in structs) {
            if (s.fields.isNotEmpty()) structNames += nameResolver.resolveName(s)
        }
        for (c in classes) {
            classNames += nameResolver.resolveName(c)
        }

        files += GeneratedFile(generateBaseClass(), "$WRAPPER_DIR/$baseFileName.ts")
        files += GeneratedFile(generateErrorClass(), "$WRAPPER_DIR/$errorClassName.ts")

        for (e in enums) {
            val name = nameResolver.resolveName(e)
            val content = generateEnum(e, name)
            if (content != null) {
                files += GeneratedFile(content, "$WRAPPER_DIR/$name.ts")
                generatedNames += name
            }
        }

        for (s in structs) {
            if (s.fields.isEmpty()) continue
            val name = nameResolver.resolveName(s)
            files += GeneratedFile(generateStruct(s, name), "$WRAPPER_DIR/$name.ts")
            generatedNames += name
        }

        for (c in classes) {
            val name = nameResolver.resolveName(c)
            files += GeneratedFile(generateClass(c, name), "$WRAPPER_DIR/$name.ts")
            generatedNames += name
        }

        files += GeneratedFile(generateIndex(), "$WRAPPER_DIR/index.ts")
        return files
    }

    // ── Enum ──────────────────────────────────────────────────────────────────

    private fun generateEnum(
        e: LimeEnumeration,
        name: String,
    ): String? {
        if (e.enumerators.isEmpty()) return null
        val lines = mutableListOf<String>()
        lines += "// Auto-generated by Gluecodium. Do not modify."
        lines += ""
        lines += "export enum $name {"
        for ((i, enumerator) in e.enumerators.withIndex()) {
            val enumName = enumerator.path.tail.last().uppercase()
            lines += "  $enumName = $i,"
        }
        lines += "}"
        lines += ""
        return lines.joinToString("\n")
    }

    // ── Struct ────────────────────────────────────────────────────────────────

    /**
     * Determines what make() signature the spec will have for this struct.
     * Returns the list of parameter names, or null if no make() exists in the spec.
     */
    private fun getSpecMakeParams(s: LimeStruct): List<LimeParameter>? {
        // Priority: explicit constructors, then field constructors, then synthetic make
        val fieldConstructorFunctions = s.fieldConstructors.map { it.asFunction() }
        val allCtors =
            (s.constructors + fieldConstructorFunctions)
                .filter { !shouldExcludeFunction(it) }
                .orderedByPrimaryThenArity()

        if (allCtors.isNotEmpty()) {
            return allCtors.first().parameters
        }

        // Synthetic make: undefaulted fields as params — empty for all-defaulted structs (→ no-arg
        // make(), Phase 23.2); r,g,b,a for the external Color struct (Phase 23.6-C). The TS spec + C++
        // generator emit a matching make() signature. Reached when NO ctor is exposed — either there
        // are no LIME ctors, or all are excluded by shouldExcludeFunction (@Skip(Java)+@Skip(Swift)),
        // e.g. a struct with no exposed constructor. `allCtors` is already known empty here.
        if (s.fields.isNotEmpty()) {
            return s.uninitializedFields.map { LimeParameter(it.path, typeRef = it.typeRef) }
        }

        return null // No make in spec
    }

    private fun generateStruct(
        s: LimeStruct,
        name: String,
    ): String {
        val moduleName = "Native${name}Module"
        val deps = mutableSetOf<String>()
        collectFieldDeps(s, deps)
        deps -= name
        val allKnownTypes = structNames + classNames + enumNames
        deps.retainAll(allKnownTypes)

        val specMakeParams = getSpecMakeParams(s)
        val hasMake = specMakeParams != null
        // Phase 23.11: when the struct's exposed ctors omit fields (e.g. Location), _toHandle
        // round-trips losslessly via the generated makeFull(all fields) instead of the lossy make().
        val makeFullFieldList = makeFullFields(s) { shouldExcludeFunction(it) }

        val lines = mutableListOf<String>()
        lines += "// Auto-generated by Gluecodium. Do not modify."
        lines += "import $moduleName from '../specs/$moduleName';"
        for (dep in deps.sorted()) {
            lines += "import { $dep } from './$dep';"
        }
        lines += ""
        lines += "export class $name {"

        // Constructor selection (computed early so backing-field decls below can see ctor params).
        val fieldCtor = s.fieldConstructors.orderedFieldCtorsByPrimaryThenArity().firstOrNull()
        val regularCtor =
            s.constructors
                .filter { !shouldExcludeFunction(it) }
                .orderedByPrimaryThenArity()
                .firstOrNull()

        // Fields — use | undefined for nullable, readonly T[] for lists
        for (field in s.fields) {
            val fieldName = toCamelCase(field.path.tail.last())
            val tsType = resolveFieldType(field.typeRef)
            lines += "  readonly $fieldName: $tsType;"
        }
        // Backing fields for ctor params that are NOT struct fields (e.g. a make()-only param such
        // as MapMeasureDependentRenderSize.size); _toHandle passes this.<param>, so it must be stored.
        val structFieldNames = s.fields.map { toCamelCase(it.path.tail.last()) }.toSet()
        val extraCtorParams =
            (regularCtor?.parameters ?: emptyList())
                .filter { toCamelCase(it.path.tail.last()) !in structFieldNames }
        for (p in extraCtorParams) {
            lines += "  readonly ${toCamelCase(p.path.tail.last())}: ${resolveType(p.typeRef)};"
        }
        lines += ""

        // Constructor — sort optional params to end
        when {
            fieldCtor != null -> {
                val requiredNames = fieldCtor.fields.map { it.path.tail.last() }.toSet()
                val requiredFields = s.fields.filter { it.path.tail.last() in requiredNames && !it.typeRef.isNullable }
                val optionalFields = s.fields.filter { it !in requiredFields }

                val sortedFields = requiredFields + optionalFields
                val ctorParams =
                    sortedFields.map { field ->
                        val fieldName = toCamelCase(field.path.tail.last())
                        val tsType = resolveType(field.typeRef)
                        val isRequired = field in requiredFields
                        if (isRequired) "$fieldName: $tsType" else "$fieldName?: $tsType"
                    }
                lines += "  constructor(${ctorParams.joinToString(", ")}) {"
                for (field in s.fields) {
                    val fieldName = toCamelCase(field.path.tail.last())
                    if (field in requiredFields) {
                        lines += "    this.$fieldName = $fieldName;"
                    } else {
                        val default = getFieldDefault(field.typeRef)
                        lines += "    this.$fieldName = $fieldName ?? $default;"
                    }
                }
                lines += "  }"
            }
            regularCtor != null -> {
                val ctorParams =
                    regularCtor.parameters.map { p ->
                        val pName = toCamelCase(p.path.tail.last())
                        val tsType = resolveType(p.typeRef)
                        "$pName: $tsType"
                    }
                lines += "  constructor(${ctorParams.joinToString(", ")}) {"
                val ctorParamNames = regularCtor.parameters.map { toCamelCase(it.path.tail.last()) }.toSet()
                for (field in s.fields) {
                    val fieldName = toCamelCase(field.path.tail.last())
                    if (fieldName in ctorParamNames) {
                        lines += "    this.$fieldName = $fieldName;"
                    } else {
                        lines += "    this.$fieldName = ${getFieldDefault(field.typeRef)};"
                    }
                }
                // Store ctor params that aren't struct fields (so _toHandle can pass them).
                for (p in extraCtorParams) {
                    val pName = toCamelCase(p.path.tail.last())
                    lines += "    this.$pName = $pName;"
                }
                lines += "  }"
            }
            else -> {
                // All fields constructor — sort optional to end
                val requiredFields = s.fields.filter { !it.typeRef.isNullable }
                val optionalFields = s.fields.filter { it.typeRef.isNullable }
                val sortedFields = requiredFields + optionalFields
                val ctorParams =
                    sortedFields.map { field ->
                        val fieldName = toCamelCase(field.path.tail.last())
                        val tsType = resolveType(field.typeRef)
                        if (field.typeRef.isNullable) "$fieldName?: $tsType" else "$fieldName: $tsType"
                    }
                lines += "  constructor(${ctorParams.joinToString(", ")}) {"
                for (field in s.fields) {
                    val fieldName = toCamelCase(field.path.tail.last())
                    if (field.typeRef.isNullable) {
                        lines += "    this.$fieldName = $fieldName ?? undefined;"
                    } else {
                        lines += "    this.$fieldName = $fieldName;"
                    }
                }
                lines += "  }"
            }
        }
        lines += ""

        // _toHandle — only emit if spec has make()
        if (hasMake) {
            lines += "  /** @internal */"
            lines += "  _toHandle(): string {"
            if (makeFullFieldList != null) {
                // Lossless round-trip: marshal every field through the generated makeFull.
                val fullArgs =
                    makeFullFieldList.map { field ->
                        marshalToNative("this.${toCamelCase(field.path.tail.last())}", field.typeRef)
                    }
                lines += "    return $moduleName.makeFull(${fullArgs.joinToString(", ")});"
            } else {
                val makeArgs =
                    specMakeParams!!.map { param ->
                        val paramName = toCamelCase(param.path.tail.last())
                        marshalToNative("this.$paramName", param.typeRef)
                    }
                lines += "    return $moduleName.make(${makeArgs.joinToString(", ")});"
            }
            lines += "  }"
        } else {
            // No make available — _toHandle throws at runtime
            lines += "  /** @internal */"
            lines += "  _toHandle(): string {"
            lines += "    throw new Error('$name._toHandle: no make() available in spec');"
            lines += "  }"
        }
        lines += ""

        // _fromHandle
        lines += "  /** @internal */"
        lines += "  static _fromHandle(__handle: string): $name {"
        val reservedNames = setOf("create", "getConstants", "getName")
        for (field in s.fields) {
            val fieldName = toCamelCase(field.path.tail.last())
            val upperCamel = toCamelCase(field.path.tail.last()).replaceFirstChar { it.uppercase() }
            var getter = "get$upperCamel"
            if (getter in reservedNames) getter = "getField$upperCamel"
            val rawExpr = "$moduleName.$getter(__handle)"
            val converted = marshalFromNativeForStructField(rawExpr, field.typeRef, fieldName, lines)
            lines += "    const $fieldName = $converted;"
        }
        lines += "    $moduleName.release(__handle);"
        lines += "    const __instance = Object.create($name.prototype) as $name;"
        for (field in s.fields) {
            val fieldName = toCamelCase(field.path.tail.last())
            lines += "    ((__instance as any).$fieldName) = $fieldName;"
        }
        lines += "    return __instance;"
        lines += "  }"

        // fromDefaults() (design §1.5): a no-argument native factory produces `fromDefaults()` when
        // the normal wrapper constructor requires explicit fields. The idiomatic constructor demands
        // the struct's required fields, but the SDK still ships a defaulted instance via the no-arg
        // native make(); we delegate to it and reconstruct through _fromHandle so ownership/release
        // metadata match every other wrapper. Emitted ONLY when the selected native factory is
        // genuinely ZERO-argument (specMakeParams empty) AND the wrapper constructor is non-empty
        // (otherwise `new T()` already yields the default). Guarding on the make arity is essential:
        // a struct whose only make() requires arguments (e.g. AddressQuery.make(query)) must NOT get a
        // `fromDefaults()` that calls make() with no args — that is a TS2554 type error.
        val nativeMakeIsZeroArg = specMakeParams != null && specMakeParams.isEmpty()
        if (hasMake && nativeMakeIsZeroArg && wrapperConstructorRequiresArguments(s)) {
            lines += ""
            lines += "  /** Create an instance initialized with the native SDK defaults. */"
            lines += "  static fromDefaults(): $name {"
            lines += "    return $name._fromHandle($moduleName.make());"
            lines += "  }"
        }
        lines += "}"
        lines += ""
        return lines.joinToString("\n")
    }

    /**
     * Whether the idiomatic wrapper constructor emitted for [s] demands at least one explicit
     * argument. Mirrors the constructor-selection branches in [generateStruct]: a field or regular
     * constructor takes its (required) parameters; otherwise the all-fields constructor takes every
     * non-nullable field. An empty parameter list means `new T()` already produces the default, so no
     * separate `fromDefaults()` is needed.
     */
    private fun wrapperConstructorRequiresArguments(s: LimeStruct): Boolean {
        val fieldCtor = s.fieldConstructors.orderedFieldCtorsByPrimaryThenArity().firstOrNull()
        val regularCtor =
            s.constructors
                .filter { !shouldExcludeFunction(it) }
                .orderedByPrimaryThenArity()
                .firstOrNull()
        return when {
            fieldCtor != null -> {
                val requiredNames = fieldCtor.fields.map { it.path.tail.last() }.toSet()
                s.fields.any { it.path.tail.last() in requiredNames && !it.typeRef.isNullable }
            }
            regularCtor != null -> regularCtor.parameters.isNotEmpty()
            else -> s.fields.any { !it.typeRef.isNullable }
        }
    }

    // ── Class ─────────────────────────────────────────────────────────────────

    /**
     * Gets method names that the spec will actually expose for this class.
     */
    private fun getSpecMethodNames(c: LimeClass): Set<String> {
        val seenNames = mutableSetOf("create", "getConstants", "getName")
        val names = mutableSetOf<String>()

        // Constructors
        for (ctor in c.constructors) {
            if (shouldExcludeFunction(ctor)) continue
            val name = nameResolver.resolveName(ctor)
            if (seenNames.add(name)) names += name
        }

        // Release
        seenNames += "release"

        // Methods
        val inheritedFunctions = c.interfaceInheritedFunctions.filter { !it.isConstructor }
        val orderedMethods =
            (c.functions.filter { !it.isConstructor } + inheritedFunctions)
                .filter { !shouldExcludeFunction(it) }
                .sortedBy { it.parameters.size }
        for (func in orderedMethods) {
            val name =
                TurboModuleCallableNameResolver.resolveEffectiveName(func, seenNames)
                    ?: continue
            names += name
        }

        // Property getters (skip interface-typed). Include inherited interface properties so that,
        // like the spec and bridge emitters, the wrapper exposes accessors it inherits from a parent
        // interface (e.g. a property inherited from a parent interface).
        val allProperties = c.properties + c.interfaceInheritedProperties
        for (prop in allProperties) {
            val actualType = prop.typeRef.type.actualType
            if (actualType is LimeLambda || isPlatformSpecificType(actualType)) continue
            if (actualType is LimeInterface) continue
            val getterName = "get${prop.path.name.split("_").joinToString("") { it.replaceFirstChar { ch -> ch.uppercase() } }}"
            if (seenNames.add(getterName)) names += getterName
        }

        // Property setters
        for (prop in allProperties) {
            if (prop.setter == null) continue
            val actualType = prop.typeRef.type.actualType
            if (actualType is LimeLambda || isPlatformSpecificType(actualType)) continue
            val setterName = "set${prop.path.name.split("_").joinToString("") { it.replaceFirstChar { ch -> ch.uppercase() } }}"
            if (seenNames.add(setterName)) names += setterName
        }

        return names
    }

    private fun generateClass(
        c: LimeClass,
        name: String,
    ): String {
        val moduleName = "Native${name}Module"
        val deps = mutableSetOf<String>()
        collectClassDeps(c, deps)
        deps -= name
        val allKnownTypes = structNames + classNames + enumNames
        deps.retainAll(allKnownTypes)

        val specMethodNames = getSpecMethodNames(c)

        val lines = mutableListOf<String>()
        lines += "// Auto-generated by Gluecodium. Do not modify."
        lines += "import $moduleName from '../specs/$moduleName';"
        lines += "import { $baseClassName } from './$baseFileName';"
        lines += "import { $errorClassName } from './$errorClassName';"
        for (dep in deps.sorted()) {
            lines += "import { $dep } from './$dep';"
        }
        lines += ""
        lines += "export class $name extends $baseClassName {"

        // Constructor — select the same one the spec picks (sorted by param count, first wins)
        val hasFactory = c.constructors.isNotEmpty() && c.constructors.any { !shouldExcludeFunction(it) }
        // Reserve effective constructor names in the SAME order the spec/bridge resolver walks them,
        // so a @Dart(Name) overload surfaces here under the identical alternate name. The first
        // constructor claims the base name `make` and becomes the idiomatic JS constructor; every
        // additional constructor becomes a NAMED static factory (design §1.5, e.g. Type.makeFromPath).
        val exposedConstructors =
            c.constructors
                .filter { !shouldExcludeFunction(it) }
                .sortedBy { it.parameters.size }
        val constructorSeenNames = mutableSetOf("create", "getConstants", "getName")
        val primaryConstructor = exposedConstructors.firstOrNull()
        if (primaryConstructor != null) {
            TurboModuleCallableNameResolver.resolveEffectiveName(primaryConstructor, constructorSeenNames)
        }
        if (hasFactory) {
            val ctor = primaryConstructor!!
            if (ctor.parameters.isEmpty()) {
                lines += "  constructor() {"
                lines += "    super($moduleName.make(), $moduleName);"
                lines += "  }"
            } else {
                val params =
                    ctor.parameters.joinToString(", ") { p ->
                        val pName = toCamelCase(p.path.tail.last())
                        "$pName: ${resolveType(p.typeRef)}"
                    }
                val args =
                    ctor.parameters.joinToString(", ") { p ->
                        val pName = toCamelCase(p.path.tail.last())
                        marshalToNative(pName, p.typeRef)
                    }
                lines += "  constructor($params) {"
                lines += "    super($moduleName.make($args), $moduleName);"
                lines += "  }"
            }
        } else {
            lines += "  /** @internal */"
            lines += "  constructor(handle: string) {"
            lines += "    super(handle, $moduleName);"
            lines += "  }"
        }
        lines += ""

        // Named static factories for every additional constructor (design §1.5). Each is reconstructed
        // via _fromHandle so ownership/release metadata match the rest of the wrapper.
        for (ctor in exposedConstructors.drop(1)) {
            val factoryName =
                TurboModuleCallableNameResolver.resolveEffectiveName(ctor, constructorSeenNames)
                    ?: continue
            val params =
                ctor.parameters.joinToString(", ") { p ->
                    "${toCamelCase(p.path.tail.last())}: ${resolveType(p.typeRef)}"
                }
            val args =
                ctor.parameters.joinToString(", ") { p ->
                    marshalToNative(toCamelCase(p.path.tail.last()), p.typeRef)
                }
            lines += "  static $factoryName($params): $name {"
            lines += "    return $name._fromHandle($moduleName.$factoryName($args));"
            lines += "  }"
            lines += ""
        }

        if (!hasFactory) {
            lines += "  /** @internal */"
            lines += "  static _fromHandle(handle: string): $name { return new $name(handle); }"
            lines += ""
        } else {
            // Even with a typed constructor, provide _fromHandle for internal deserialization
            lines += "  /** @internal */"
            lines += "  static _fromHandle(handle: string): $name {"
            lines += "    const instance = Object.create($name.prototype) as $name;"
            lines += "    (instance as any)._handle = handle;"
            lines += "    (instance as any)._module = $moduleName;"
            lines += "    (instance as any)._released = false;"
            lines += "    (instance as any)._owned = true;"
            lines += "    return instance;"
            lines += "  }"
            lines += ""
        }

        // Properties (only emit getters that exist in spec). Include inherited interface properties
        // (design §1.3) so accessors declared on a parent interface (an inherited property)
        // surface on the wrapper, matching the spec/bridge layers.
        val ownAndInheritedProperties = c.properties + c.interfaceInheritedProperties
        for (prop in ownAndInheritedProperties) {
            if (prop.getter == null) continue
            val actualType = prop.typeRef.type.actualType
            if (actualType is LimeLambda || isPlatformSpecificType(actualType)) continue
            if (actualType is LimeInterface) continue

            val propName = toCamelCase(prop.path.tail.last())
            val getterName = "get${prop.path.tail.last().split("_").joinToString("") { it.replaceFirstChar { ch -> ch.uppercase() } }}"
            if (getterName !in specMethodNames) continue

            val tsType = resolveFieldType(prop.typeRef)
            val rawExpr = "$moduleName.$getterName(this._handle)"
            val converted = marshalFromNative(rawExpr, prop.typeRef)
            lines += "  get $propName(): $tsType {"
            lines += "    return $converted;"
            lines += "  }"
            lines += ""
        }

        // Data-property setters (non-interface, non-lambda). Marshals the value to its native form
        // (object -> handle, nullable primitive/enum -> value ?? null) before calling the spec setter.
        // Interface-typed listener setters are handled separately below. Inherited interface
        // properties are included (design §1.3) — this is what the generator emits for an inherited property's
        // setter, retiring _patch_wrapper_visual_navigator.
        for (prop in ownAndInheritedProperties) {
            if (prop.setter == null) continue
            val actualType = prop.typeRef.type.actualType
            if (actualType is LimeLambda || isPlatformSpecificType(actualType)) continue
            if (actualType is LimeInterface) continue

            val setterName = "set${prop.path.tail.last().split("_").joinToString("") { it.replaceFirstChar { ch -> ch.uppercase() } }}"
            if (setterName !in specMethodNames) continue

            val propName = toCamelCase(prop.path.tail.last())
            val valueType = if (prop.typeRef.isNullable) "${resolveType(prop.typeRef)} | undefined | null" else resolveType(prop.typeRef)
            val marshalledValue = marshalToNative("value", prop.typeRef)
            lines += "  set $propName(value: $valueType) {"
            lines += "    $moduleName.$setterName(this._handle, $marshalledValue);"
            lines += "  }"
            lines += ""
        }

        // Property setters for interface-typed properties (listener pattern)
        for (prop in ownAndInheritedProperties) {
            if (prop.setter == null) continue
            val actualType = prop.typeRef.type.actualType
            if (actualType !is LimeInterface) continue
            if (actualType.functions.size != 1) continue
            val method = actualType.functions.first()
            if (method.parameters.size > 3) continue

            val setterName = "set${prop.path.tail.last().split("_").joinToString("") { it.replaceFirstChar { ch -> ch.uppercase() } }}"
            if (setterName !in specMethodNames) continue

            val propName = toCamelCase(prop.path.tail.last())
            val cbParams =
                method.parameters.joinToString(", ") { p ->
                    "${p.path.name}: ${mapCallbackParamType(p.typeRef)}"
                }
            val cbReturnType = mapCallbackParamType(method.returnType.typeRef)
            val cbType = if (prop.typeRef.isNullable) "(($cbParams) => $cbReturnType) | null" else "($cbParams) => $cbReturnType"
            lines += "  set $propName(value: $cbType) {"
            lines += "    $moduleName.$setterName(this._handle, value);"
            lines += "  }"
            lines += ""
        }

        // Methods (only emit methods that exist in spec). Reserve names in the SAME order the
        // spec/bridge use so the shared resolver yields identical effective names: constructors
        // first (all -> "make"), then release, then methods sorted by arity. This lets an overload
        // disambiguated via @Dart(Name) surface under its alternate name in the wrapper too.
        val methodSeenNames = mutableSetOf("create", "getConstants", "getName")
        for (ctor in c.constructors) {
            if (shouldExcludeFunction(ctor)) continue
            TurboModuleCallableNameResolver.resolveEffectiveName(ctor, methodSeenNames)
        }
        methodSeenNames += "release"
        val inheritedFunctions = c.interfaceInheritedFunctions.filter { !it.isConstructor }
        val orderedFunctions =
            (c.functions.filter { !it.isConstructor } + inheritedFunctions)
                .filter { !shouldExcludeFunction(it) }
                .sortedBy { it.parameters.size }
        for (func in orderedFunctions) {
            val methodName =
                TurboModuleCallableNameResolver.resolveEffectiveName(func, methodSeenNames)
                    ?: continue
            if (methodName !in specMethodNames) continue

            val params = func.parameters
            val lastParam = params.lastOrNull()
            val isAsync = lastParam != null && isCallbackType(lastParam.typeRef)

            if (isAsync) {
                generateAsyncMethod(lines, name, moduleName, methodName, params, lastParam!!.typeRef, func.isStatic)
            } else {
                generateSyncMethod(lines, moduleName, methodName, params, func.returnType.typeRef, func.isStatic)
            }
            lines += ""
        }

        if ("dispose" !in methodSeenNames) {
            lines += "  dispose(): void { this._release(); }"
            lines += "  [Symbol.dispose](): void { this._release(); }"
        }
        lines += "}"
        lines += ""
        return lines.joinToString("\n")
    }

    private fun generateAsyncMethod(
        lines: MutableList<String>,
        className: String,
        moduleName: String,
        methodName: String,
        params: List<LimeParameter>,
        callbackTypeRef: LimeTypeRef,
        isStatic: Boolean = false,
    ) {
        val lambda = callbackTypeRef.type.actualType as? LimeLambda
        val callbackParams = params.dropLast(1)
        val methodParams =
            callbackParams.map { p ->
                "${toCamelCase(p.path.tail.last())}: ${resolveParamType(p.typeRef)}"
            }

        // Determine the return type from the lambda's params (last param = error, second-to-last = result)
        // But not all lambdas follow this pattern. Use a generic approach:
        // If lambda has 2+ params and first param is nullable enum → error/result pattern
        // Otherwise just wrap the raw callback params
        val lambdaParams = lambda?.parameters ?: emptyList()
        val isErrorResultPattern =
            lambdaParams.size >= 2 &&
                lambdaParams[0].typeRef.isNullable &&
                lambdaParams[0].typeRef.type.actualType is LimeEnumeration

        // A static async method is a FACTORY (design §1.5, e.g. Type.fromEngine): it must be
        // emitted as `static ...(): Promise<T>`, must NOT pass `this._handle` as the first native arg,
        // and resolves through T._fromHandle. An instance async method keeps `this._handle` first.
        val staticMod = if (isStatic) "static " else ""

        if (isErrorResultPattern) {
            val returnType = resolveAsyncReturnType(callbackTypeRef)
            lines += "  $staticMod$methodName(${methodParams.joinToString(", ")}): Promise<$returnType> {"
            lines += "    return new Promise((resolve, reject) => {"
            val nativeArgs = if (isStatic) mutableListOf() else mutableListOf("this._handle")
            for (p in callbackParams) {
                val pName = toCamelCase(p.path.tail.last())
                nativeArgs += marshalToNative(pName, p.typeRef)
            }
            // Build callback param signature matching the spec's lambda type
            val cbParamSig =
                lambdaParams.joinToString(", ") { p ->
                    "${p.path.name}: ${mapCallbackParamType(p.typeRef)}"
                }
            lines += "      $moduleName.$methodName("
            lines += "        ${nativeArgs.joinToString(", ")},"
            lines += "        ($cbParamSig) => {"
            lines += "          if (${lambdaParams[0].path.name} !== null) {"
            lines += "            reject(new $errorClassName('$className.$methodName failed', ${lambdaParams[0].path.name}));"
            lines += "          } else {"
            val resultWrap = buildResultWrapExpr(callbackTypeRef)
            lines += "            resolve($resultWrap);"
            lines += "          }"
            lines += "        }"
            lines += "      );"
            lines += "    });"
            lines += "  }"
        } else {
            // Non-standard callback — just pass through as a synchronous call with a callback arg
            // Generate as a regular method that takes a callback parameter
            val allMethodParams =
                params.map { p ->
                    "${toCamelCase(p.path.tail.last())}: ${resolveType(p.typeRef)}"
                }
            val nativeArgs =
                (if (isStatic) emptyList() else listOf("this._handle")) +
                    params.map { p ->
                        marshalToNative(toCamelCase(p.path.tail.last()), p.typeRef)
                    }
            lines += "  $staticMod$methodName(${allMethodParams.joinToString(", ")}): void {"
            lines += "    $moduleName.$methodName(${nativeArgs.joinToString(", ")});"
            lines += "  }"
        }
    }

    private fun mapCallbackParamType(typeRef: LimeTypeRef): String {
        val actual = typeRef.type.actualType
        val nullable = typeRef.isNullable
        return when {
            actual is LimeBasicType -> {
                val base =
                    when (actual.typeId) {
                        LimeBasicType.TypeId.VOID -> "void"
                        LimeBasicType.TypeId.BOOLEAN -> "boolean"
                        LimeBasicType.TypeId.STRING -> "string"
                        else -> "number"
                    }
                if (nullable && base != "void") "$base | null" else base
            }
            actual is LimeEnumeration -> if (nullable) "number | null" else "number"
            actual is LimeList -> "any"
            else -> if (nullable) "string | null" else "string"
        }
    }

    private fun generateSyncMethod(
        lines: MutableList<String>,
        moduleName: String,
        methodName: String,
        params: List<LimeParameter>,
        returnTypeRef: LimeTypeRef,
        isStatic: Boolean = false,
    ) {
        val methodParams =
            params.map { p ->
                "${toCamelCase(p.path.tail.last())}: ${resolveParamType(p.typeRef)}"
            }
        val returnType = resolveReturnType(returnTypeRef)
        val nativeArgs =
            if (isStatic) {
                params.map { p -> marshalToNative(toCamelCase(p.path.tail.last()), p.typeRef) }
            } else {
                listOf("this._handle") +
                    params.map { p ->
                        marshalToNative(toCamelCase(p.path.tail.last()), p.typeRef)
                    }
            }
        val staticMod = if (isStatic) "static " else ""
        val rawCall = "$moduleName.$methodName(${nativeArgs.joinToString(", ")})"
        val marshalledReturn = marshalFromNative(rawCall, returnTypeRef)
        val returnPrefix = if (returnType != "void") "return " else ""
        lines += "  ${staticMod}$methodName(${methodParams.joinToString(", ")}): $returnType {"
        if (returnType == "void") {
            lines += "    $rawCall;"
        } else {
            lines += "    ${returnPrefix}$marshalledReturn;"
        }
        lines += "  }"
    }

    // ── Import/Dependency Tracking ────────────────────────────────────────────

    private fun collectFieldDeps(
        s: LimeStruct,
        deps: MutableSet<String>,
    ) {
        for (field in s.fields) collectTypeDeps(field.typeRef, deps)
        // Also walk the parameter types of the constructor(s) the emitter renders. A make()-only
        // constructor parameter that is NOT a reconstructed struct field (e.g. DesiredCatalog.version
        // or MapMeasureDependentColor.color) is referenced in the emitted `constructor(...)` signature
        // and must therefore be imported, or the wrapper has a dangling type name (TS2304).
        val fieldConstructorFunctions = s.fieldConstructors.map { it.asFunction() }
        for (ctor in (s.constructors + fieldConstructorFunctions).filter { !shouldExcludeFunction(it) }) {
            for (p in ctor.parameters) collectTypeDeps(p.typeRef, deps)
        }
    }

    private fun collectClassDeps(
        c: LimeClass,
        deps: MutableSet<String>,
    ) {
        for (prop in (c.properties + c.interfaceInheritedProperties)) collectTypeDeps(prop.typeRef, deps)
        for (ctor in c.constructors) {
            for (p in ctor.parameters) collectTypeDeps(p.typeRef, deps)
        }
        val inheritedFunctions = c.interfaceInheritedFunctions.filter { !it.isConstructor }
        for (func in (c.functions + inheritedFunctions)) {
            if (func.isConstructor) continue
            for (p in func.parameters) collectTypeDeps(p.typeRef, deps)
            collectTypeDeps(func.returnType.typeRef, deps)
            val lastParam = func.parameters.lastOrNull()
            if (lastParam != null && isCallbackType(lastParam.typeRef)) {
                val lambda = lastParam.typeRef.type.actualType as? LimeLambda
                lambda?.parameters?.forEach { collectTypeDeps(it.typeRef, deps) }
            }
        }
    }

    private fun collectTypeDeps(
        typeRef: LimeTypeRef,
        deps: MutableSet<String>,
    ) {
        val actual = typeRef.type.actualType
        when (actual) {
            is LimeStruct -> deps += nameResolver.resolveName(actual)
            is LimeClass -> deps += nameResolver.resolveName(actual)
            is LimeEnumeration -> deps += nameResolver.resolveName(actual)
            is LimeList -> collectTypeDeps(actual.elementType, deps)
            is LimeMap -> {
                // A Map<K,V> reconstructs its key/value in the emitted body via `K._fromHandle(...)`
                // / `V._fromHandle(...)`, so both sides are import dependencies (mirrors the List
                // element-type recursion above). Without this the wrapper names a type it never
                // imports (TS2304) — the gap the repair_dangling_wrapper_refs.py sync-step covered.
                collectTypeDeps(actual.keyType, deps)
                collectTypeDeps(actual.valueType, deps)
            }
        }
    }

    // ── Marshalling ───────────────────────────────────────────────────────────

    private fun marshalToNative(
        expr: String,
        typeRef: LimeTypeRef,
    ): String {
        val actual = typeRef.type.actualType
        val typeName =
            when (actual) {
                is LimeStruct -> nameResolver.resolveName(actual)
                is LimeClass -> nameResolver.resolveName(actual)
                else -> null
            }
        val nullable = typeRef.isNullable
        return when {
            typeName != null && typeName in structNames ->
                if (nullable) "$expr?._toHandle() ?? null" else "$expr!._toHandle()"
            typeName != null && typeName in classNames ->
                if (nullable) "$expr?._nativeHandle ?? null" else "$expr!._nativeHandle"
            actual is LimeList -> {
                val elemType = actual.elementType.type.actualType
                val elemName =
                    when (elemType) {
                        is LimeStruct -> nameResolver.resolveName(elemType)
                        is LimeClass -> nameResolver.resolveName(elemType)
                        else -> null
                    }
                when {
                    elemName != null && elemName in structNames -> "($expr ?? []).map(e => e._toHandle())"
                    elemName != null && elemName in classNames -> "($expr ?? []).map(e => e._nativeHandle)"
                    else -> "($expr ?? []) as any"
                }
            }
            nullable && (actual is LimeBasicType || actual is LimeEnumeration) ->
                "$expr ?? null"
            actual is LimeMap -> {
                // Serialize a Map<K,V> to an array of [key,value] tuples for the TurboModule boundary,
                // converting wrapper-class sides to their native handles (spec task 15.3).
                val keyConv = mapSideToNative("e[0]", actual.keyType)
                val valConv = mapSideToNative("e[1]", actual.valueType)
                if (keyConv == "e[0]" && valConv == "e[1]") {
                    "[...($expr ?? new Map())]"
                } else {
                    "[...($expr ?? new Map())].map(e => [$keyConv, $valConv])"
                }
            }
            else -> expr
        }
    }

    /** Convert one map key/value from its idiomatic wrapper form to the native handle/scalar. */
    private fun mapSideToNative(
        expr: String,
        typeRef: LimeTypeRef,
    ): String {
        val name =
            when (val actual = typeRef.type.actualType) {
                is LimeStruct -> nameResolver.resolveName(actual)
                is LimeClass -> nameResolver.resolveName(actual)
                else -> null
            }
        return when {
            name != null && name in structNames -> "($expr as any)._toHandle()"
            name != null && name in classNames -> "($expr as any)._nativeHandle"
            else -> expr
        }
    }

    /**
     * Reconstruct one STRUCT FIELD from its native getter during struct `_fromHandle`.
     *
     * Differs from [marshalFromNative] only for NON-NULLABLE nested class/struct fields: the SDK can
     * legitimately return a null handle for a field the LIME model marks non-nullable during live,
     * transient states (e.g. RouteProgress.route / routeMatchedLocation before a map-match lock is
     * acquired on early navigation ticks). With the null-handle hardening, an eager
     * `Type._fromHandle(nullHandle)` THROWS, and because struct `_fromHandle` reconstructs ALL fields
     * eagerly, one transient-null nested field would abort the WHOLE struct — dropping the sibling
     * fields the caller actually needs (e.g. sectionProgress). To keep the struct reconstruction
     * resilient, a non-nullable nested class/struct field is rebuilt only when its handle is present
     * and left `undefined` otherwise, exactly like a nullable field. The native getter is bound to a
     * single local so it is invoked once (no double FFI call). All other field kinds (primitives,
     * enums, lists, maps, already-nullable classes/structs) are delegated verbatim to
     * [marshalFromNative].
     */
    private fun marshalFromNativeForStructField(
        expr: String,
        typeRef: LimeTypeRef,
        fieldName: String,
        lines: MutableList<String>,
    ): String {
        val actual = typeRef.type.actualType
        val typeName =
            when (actual) {
                is LimeStruct -> nameResolver.resolveName(actual)
                is LimeClass -> nameResolver.resolveName(actual)
                else -> null
            }
        val isNestedNonNullable =
            !typeRef.isNullable && typeName != null && (typeName in structNames || typeName in classNames)
        if (isNestedNonNullable) {
            // Bind the getter once so we do not call the native FFI twice in the ternary, then rebuild
            // only when the handle is present AND non-empty. The C++ field getter returns an EMPTY
            // string (not a throw) when the native field handle is null during transient SDK states,
            // so an empty handle means "absent": leaving it undefined keeps the struct's other fields
            // intact instead of throwing "Invalid native handle" from the whole reconstruction.
            val rawLocal = "${fieldName}__rawHandle"
            lines += "    const $rawLocal = $expr;"
            return "(($rawLocal) != null && ($rawLocal) !== '' ? $typeName._fromHandle(($rawLocal)!) : undefined)"
        }
        return marshalFromNative(expr, typeRef)
    }

    private fun marshalFromNative(
        expr: String,
        typeRef: LimeTypeRef,
    ): String {
        val actual = typeRef.type.actualType
        val typeName =
            when (actual) {
                is LimeStruct -> nameResolver.resolveName(actual)
                is LimeClass -> nameResolver.resolveName(actual)
                else -> null
            }
        val allKnownTypes = structNames + classNames
        return when {
            typeName != null && typeName in structNames ->
                if (typeRef.isNullable) {
                    "(($expr) != null ? $typeName._fromHandle(($expr)!) : undefined)"
                } else {
                    "$typeName._fromHandle($expr)"
                }
            typeName != null && typeName in classNames ->
                if (typeRef.isNullable) {
                    "(($expr) != null ? $typeName._fromHandle(($expr)!) : undefined)"
                } else {
                    "$typeName._fromHandle($expr)"
                }
            actual is LimeList -> {
                val elemActual = actual.elementType.type.actualType
                val elemName =
                    when (elemActual) {
                        is LimeStruct -> nameResolver.resolveName(elemActual)
                        is LimeClass -> nameResolver.resolveName(elemActual)
                        else -> null
                    }
                when {
                    elemName != null && elemName in structNames ->
                        "($expr as string[])?.map((h: string) => $elemName._fromHandle(h)) ?? []"
                    elemName != null && elemName in classNames ->
                        "($expr as string[])?.map((h: string) => $elemName._fromHandle(h)) ?? []"
                    // Non-class/struct element lists (enums, primitives): the native call returns the
                    // already-idiomatic values (enum ordinals as numbers, primitives as-is), so the
                    // list needs no per-element reconstruction. Cast to the resolved element type
                    // rather than widening to `any` (design §1.6: wrappers SHALL NOT widen to `any`).
                    else -> "($expr ?? []) as ${resolveType(typeRef)}"
                }
            }
            typeRef.isNullable && actual is LimeBasicType -> "($expr ?? undefined)"
            typeRef.isNullable && actual is LimeEnumeration -> "($expr ?? undefined)"
            actual is LimeMap -> {
                // Reconstruct a Map<K,V> from the native array of [key,value] tuples, rebuilding
                // wrapper-class sides via _fromHandle (spec task 15.3).
                val keyConv = mapSideFromNative("e[0]", actual.keyType)
                val valConv = mapSideFromNative("e[1]", actual.valueType)
                val kv = resolveType(typeRef).removePrefix("Map<").removeSuffix(">")
                if (keyConv == "e[0]" && valConv == "e[1]") {
                    "new Map(($expr ?? []) as [$kv][])"
                } else {
                    "new Map((($expr ?? []) as any[]).map((e: any) => [$keyConv, $valConv]))"
                }
            }
            else -> expr
        }
    }

    /** Convert one map key/value from its native handle/scalar to the idiomatic wrapper form. */
    private fun mapSideFromNative(
        expr: String,
        typeRef: LimeTypeRef,
    ): String {
        val name =
            when (val actual = typeRef.type.actualType) {
                is LimeStruct -> nameResolver.resolveName(actual)
                is LimeClass -> nameResolver.resolveName(actual)
                else -> null
            }
        return when {
            name != null && (name in structNames || name in classNames) -> "$name._fromHandle($expr as string)"
            else -> expr
        }
    }

    // ── Index ─────────────────────────────────────────────────────────────────

    private fun generateIndex(): String {
        val lines = mutableListOf<String>()
        lines += "// Auto-generated by Gluecodium. Do not modify."
        lines += "export { $baseClassName } from './$baseFileName';"
        lines += "export { $errorClassName } from './$errorClassName';"
        for (name in generatedNames.sorted()) {
            lines += "export { $name } from './$name';"
        }
        lines += ""
        return lines.joinToString("\n")
    }

    // ── Type Resolution ───────────────────────────────────────────────────────

    /** Resolves the TS type for a field declaration (uses readonly T[] for lists, T | undefined for nullable). */
    private fun resolveFieldType(typeRef: LimeTypeRef): String {
        val base = resolveType(typeRef)
        if (typeRef.isNullable) return "$base | undefined"
        return base
    }

    private fun resolveType(typeRef: LimeTypeRef): String {
        val actual = typeRef.type.actualType
        val allKnownTypes = structNames + classNames + enumNames
        return when (actual) {
            is LimeBasicType ->
                when (actual.typeId) {
                    LimeBasicType.TypeId.BOOLEAN -> "boolean"
                    LimeBasicType.TypeId.FLOAT, LimeBasicType.TypeId.DOUBLE,
                    LimeBasicType.TypeId.INT8, LimeBasicType.TypeId.INT16,
                    LimeBasicType.TypeId.INT32, LimeBasicType.TypeId.INT64,
                    LimeBasicType.TypeId.UINT8, LimeBasicType.TypeId.UINT16,
                    LimeBasicType.TypeId.UINT32, LimeBasicType.TypeId.UINT64,
                    -> "number"
                    LimeBasicType.TypeId.STRING -> "string"
                    LimeBasicType.TypeId.DURATION -> "number"
                    else -> "any"
                }
            is LimeEnumeration -> {
                val n = nameResolver.resolveName(actual)
                if (n in allKnownTypes) n else "number"
            }
            is LimeStruct -> {
                val n = nameResolver.resolveName(actual)
                if (n in allKnownTypes) n else "any"
            }
            is LimeClass -> {
                val n = nameResolver.resolveName(actual)
                if (n in allKnownTypes) n else "any"
            }
            is LimeList -> {
                val inner = resolveType(actual.elementType)
                if (actual.elementType.type.actualType is LimeList) {
                    "readonly ($inner)[]"
                } else {
                    "readonly $inner[]"
                }
            }
            // A map is exposed idiomatically as a real Map<K, V> (spec task 15.3). Complex key/value
            // types that are not generated wrapper classes fall back to the opaque handle string.
            is LimeMap -> "Map<${resolveMapSideType(actual.keyType)}, ${resolveMapSideType(actual.valueType)}>"
            else -> "any"
        }
    }

    /** TS type for one side (key/value) of a map. Wrapper classes keep their name; scalars stay
     *  number/string/boolean; everything else is an opaque handle string. */
    private fun resolveMapSideType(typeRef: LimeTypeRef): String {
        val allKnownTypes = structNames + classNames + enumNames
        return when (val actual = typeRef.type.actualType) {
            is LimeBasicType ->
                when (actual.typeId) {
                    LimeBasicType.TypeId.BOOLEAN -> "boolean"
                    LimeBasicType.TypeId.STRING -> "string"
                    LimeBasicType.TypeId.DURATION -> "number"
                    LimeBasicType.TypeId.FLOAT, LimeBasicType.TypeId.DOUBLE,
                    LimeBasicType.TypeId.INT8, LimeBasicType.TypeId.INT16,
                    LimeBasicType.TypeId.INT32, LimeBasicType.TypeId.INT64,
                    LimeBasicType.TypeId.UINT8, LimeBasicType.TypeId.UINT16,
                    LimeBasicType.TypeId.UINT32, LimeBasicType.TypeId.UINT64,
                    -> "number"
                    else -> "string"
                }
            is LimeEnumeration -> {
                val n = nameResolver.resolveName(actual)
                if (n in allKnownTypes) n else "number"
            }
            is LimeStruct -> {
                val n = nameResolver.resolveName(actual)
                if (n in allKnownTypes) n else "string"
            }
            is LimeClass -> {
                val n = nameResolver.resolveName(actual)
                if (n in allKnownTypes) n else "string"
            }
            else -> "string"
        }
    }

    private fun resolveReturnType(typeRef: LimeTypeRef): String {
        if (typeRef.type.actualType is LimeBasicType &&
            (typeRef.type.actualType as LimeBasicType).typeId == LimeBasicType.TypeId.VOID
        ) {
            return "void"
        }
        return resolveFieldType(typeRef)
    }

    private fun isCallbackType(typeRef: LimeTypeRef): Boolean = typeRef.type.actualType is LimeLambda

    /**
     * TS type for a method PARAMETER. Mirrors [resolveType] but reflects nullability: a nullable LIME
     * parameter (e.g. `Int?`) becomes `<type> | undefined` so callers can idiomatically pass
     * `undefined`. The marshalling (`marshalToNative`) already collapses `undefined`/`null` to the
     * native `null`, so only the surface type needs widening.
     */
    private fun resolveParamType(typeRef: LimeTypeRef): String {
        val base = resolveType(typeRef)
        return if (typeRef.isNullable && base != "any") "$base | undefined" else base
    }

    private fun resolveAsyncReturnType(typeRef: LimeTypeRef): String {
        val lambda = typeRef.type.actualType as? LimeLambda ?: return "any"
        val params = lambda.parameters
        // The result is resolved only in the non-error branch, where the promisification asserts it
        // non-null (`result!`). The Promise therefore resolves the non-nullable form — an error/result
        // callback never resolves `undefined` alongside a null error. Using resolveType (not
        // resolveFieldType) drops the `| undefined` a nullable result param would otherwise add.
        return if (params.size >= 2) resolveType(params[1].typeRef) else "void"
    }

    private fun buildResultWrapExpr(callbackTypeRef: LimeTypeRef): String {
        val lambda = callbackTypeRef.type.actualType as? LimeLambda ?: return "result"
        if (lambda.parameters.size < 2) return "result"
        val resultParam = lambda.parameters[1]
        val resultName = resultParam.path.name
        val resultTypeRef = resultParam.typeRef
        val actual = resultTypeRef.type.actualType
        val allKnownTypes = structNames + classNames
        return when {
            actual is LimeList -> {
                val elemActual = actual.elementType.type.actualType
                val elemName =
                    when (elemActual) {
                        is LimeStruct -> nameResolver.resolveName(elemActual)
                        is LimeClass -> nameResolver.resolveName(elemActual)
                        else -> null
                    }
                if (elemName != null && elemName in allKnownTypes) {
                    "($resultName ?? []).map((h: string) => $elemName._fromHandle(h))"
                } else {
                    resultName
                }
            }
            actual is LimeStruct -> {
                val n = nameResolver.resolveName(actual)
                if (n in allKnownTypes) "$n._fromHandle($resultName!)" else resultName
            }
            actual is LimeClass -> {
                val n = nameResolver.resolveName(actual)
                if (n in allKnownTypes) "$n._fromHandle($resultName!)" else resultName
            }
            else -> resultName
        }
    }

    private fun getFieldDefault(typeRef: LimeTypeRef): String {
        if (typeRef.isNullable) return "undefined"
        return when (val actual = typeRef.type.actualType) {
            is LimeBasicType ->
                when (actual.typeId) {
                    LimeBasicType.TypeId.BOOLEAN -> "false"
                    LimeBasicType.TypeId.STRING -> "''"
                    else -> "0"
                }
            is LimeEnumeration -> "0"
            is LimeList -> "[]"
            is LimeMap -> "new Map()"
            else -> "undefined as any"
        }
    }

    private fun toCamelCase(snakeCase: String): String {
        val parts = snakeCase.split("_")
        return parts[0] + parts.drop(1).joinToString("") { it.replaceFirstChar { c -> c.uppercase() } }
    }

    private fun shouldExcludeFunction(func: LimeFunction): Boolean {
        if (func.parameters.any { isPlatformSpecificType(it.typeRef.type.actualType) }) return true
        if (func.attributes.have(LimeAttributeType.JAVA, LimeAttributeValueType.SKIP) &&
            func.attributes.have(LimeAttributeType.SWIFT, LimeAttributeValueType.SKIP)
        ) {
            return true
        }
        return false
    }

    private fun isPlatformSpecificType(type: LimeType): Boolean = type.attributes.have(LimeAttributeType.DART, LimeAttributeValueType.SKIP)

    private fun generateBaseClass(): String =
        """
        // Auto-generated by Gluecodium. Do not modify.

        // FinalizationRegistry may not be available in all JS engines (e.g. Hermes).
        // When unavailable, handles must be released manually via dispose().
        const _registry = typeof FinalizationRegistry !== 'undefined'
          ? new FinalizationRegistry<{ handle: string; module: any }>((ref) => {
              try { ref.module.release(ref.handle); } catch (_) {}
            })
          : null;

        export abstract class $baseClassName {
          protected _handle: string;
          private _module: any;
          private _released = false;
          private _owned: boolean;

          constructor(handle: string, module: any, owned = true) {
            this._handle = handle;
            this._module = module;
            this._owned = owned;
            if (owned) _registry?.register(this, { handle, module }, this);
          }

          protected _release(): void {
            if (!this._released && this._owned) {
              this._released = true;
              _registry?.unregister(this);
              this._module.release(this._handle);
            }
          }

          /** @internal */
          get _nativeHandle(): string { return this._handle; }
        }
        """.trimIndent()

    private fun generateErrorClass(): String =
        """
        // Auto-generated by Gluecodium. Do not modify.

        export class $errorClassName extends Error {
          readonly code: number;

          constructor(message: string, code: number) {
            super(message);
            this.name = '$errorClassName';
            this.code = code;
          }
        }
        """.trimIndent()

    companion object {
        private const val WRAPPER_DIR = "typescript/wrapper"
    }
}
