#!/bin/bash
#
# Copyright (C) 2016-2019 HERE Europe B.V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE

#
# Utility to format source code.
#

# Format CMake files with dockerized 'cmakelint'
cmake_files=$(find . \( -name CMakeLists.txt -o -name "*.cmake" \) -exec echo /opt/{} \;)
docker run \
    --net=host \
    --pid=host \
    --rm \
    --user ${UID}:${GID} \
    --volume "${PWD}:/opt" \
    saschpe/cmakelint --filter=-linelength ${cmake_files}
