package com.here.ivi.api.generator.common;

/**
 * Interface of tool that can by run on files generated by {@link GeneratorSuite#generate()}
 */
public interface IFileTool {
    /**
     * Method processing file
     * @param file file to process
     * @return processed file
     */
    GeneratedFile process(GeneratedFile file);
}
