// Auto-generated by Gluecodium. Do not modify.

import type {TurboModule} from 'react-native';
import {TurboModuleRegistry} from 'react-native';

export interface Spec extends TurboModule {
  readonly release: (__nativeHandle: string) => void
  readonly greet: (__nativeHandle: string, name: string) => string;
  readonly add: (__nativeHandle: string, a: number, b: number) => number;
}

export default TurboModuleRegistry.getEnforcing<Spec>('NativeBasicModuleModule');
