/*

 *
 */
// Generated by Gluecodium. Coroutine (suspend) support for @AsyncDecorator functions.

@file:JvmName("KotlinCoroutines_SecondaryClient")

package com.example.coroutines

import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlinx.coroutines.suspendCancellableCoroutine
import com.example.NativeBase

/**
 * Generic bridge that adapts a callback-style [startOperation] into a `suspend` call returning [Result].
 *
 * Behavior:
 * - resumes with [Result.success] carrying the callback value,
 * - resumes with [Result.failure] produced by [mapDomainError] on a domain error,
 * - fails with [IllegalStateException] if the callback breaks the (error XOR result) contract,
 * - propagates a synchronous throwable from [startOperation],
 * - cancels the underlying task via [cancelOperation] when the coroutine is cancelled before the
 *   callback resolves. The cancellation path shares the `resolved` guard with the callback, so a
 *   cancellation racing a completing callback never cancels an already-finished task.
 *
 * @param startOperation starts the underlying async operation and returns a handle.
 * @param mapDomainError converts the domain-specific error value into a [Throwable].
 * @param cancelOperation requests cancellation of the in-flight operation; the task may still
 *   complete on the native side.
 */
private suspend fun <E, T, H> awaitCoroutineResultBridge(
    startOperation: (callback: (E?, T?) -> Unit) -> H,
    mapDomainError: (E) -> Throwable,
    cancelOperation: (H) -> Unit,
): T =
    suspendCancellableCoroutine { continuation ->
        // Guards two races that `suspendCancellableCoroutine` does not cover on its own: a native callback
        // firing more than once, and `cancelOperation` running after the callback already resolved.
        val resolved = java.util.concurrent.atomic.AtomicBoolean(false)
        val handle: H? =
            try {
                startOperation { error, value ->
                    if (resolved.compareAndSet(false, true)) {
                        when {
                            error == null && value != null -> continuation.resume(value)
                            error != null && value == null -> continuation.resumeWithException(mapDomainError(error))
                            error == null && value == null ->
                                continuation.resumeWithException(IllegalStateException("Callback contract violation: both error and value are null"))
                            else ->
                                continuation.resumeWithException(IllegalStateException("Callback contract violation: both error and value are non-null"))
                        }
                    }
                }
            } catch (throwable: Throwable) {
                if (resolved.compareAndSet(false, true)) {
                    continuation.resumeWithException(throwable)
                }
                null
            }
        if (handle != null) {
            continuation.invokeOnCancellation {
                if (resolved.compareAndSet(false, true)) {
                    cancelOperation(handle)
                }
            }
        }
    }

/** Adapts a callback without a domain-error channel into a direct suspending value.
 *
 * @param startOperation starts the underlying async operation and returns a handle.
 * @param cancelOperation requests cancellation of the in-flight operation; the task may still
 *   complete on the native side.
 */
private suspend fun <T, H> awaitCoroutineValueBridge(
    startOperation: (callback: (T) -> Unit) -> H,
    cancelOperation: (H) -> Unit,
): T =
    suspendCancellableCoroutine { continuation ->
        // Guards two races that `suspendCancellableCoroutine` does not cover on its own: a native callback
        // firing more than once, and `cancelOperation` running after the callback already resolved.
        val resolved = java.util.concurrent.atomic.AtomicBoolean(false)
        val handle: H? =
            try {
                startOperation { value ->
                    if (resolved.compareAndSet(false, true)) {
                        continuation.resume(value)
                    }
                }
            } catch (throwable: Throwable) {
                if (resolved.compareAndSet(false, true)) {
                    continuation.resumeWithException(throwable)
                }
                null
            }
        if (handle != null) {
            continuation.invokeOnCancellation {
                if (resolved.compareAndSet(false, true)) {
                    cancelOperation(handle)
                }
            }
        }
    }

/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class SecondaryClientNestedClientLoadMetadataException(public val error: OperationError) : Exception(error.toString())

/** Groups multiple result values returned by the `loadMetadata` coroutine wrapper. */
public data class SecondaryClientNestedClientLoadMetadataCoroutineResult(
  public val count: Int,
  public val label: String
)

/**
 * Coroutine (`suspend`) variant of `loadMetadata`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * Cancelling the coroutine requests cancellation of the underlying task; the task may still run to completion on the native side.
 * @return the callback values grouped in a generated result type.
 * @throws SecondaryClientNestedClientLoadMetadataException on error.
 */
public suspend fun SecondaryClient.NestedClient.loadMetadata(): SecondaryClientNestedClientLoadMetadataCoroutineResult =
        awaitCoroutineResultBridge(
        startOperation = { callback -> this.loadMetadata(MultiValueCallback { error, callbackValue1, callbackValue2 -> callback(error, if (callbackValue1 != null && callbackValue2 != null) SecondaryClientNestedClientLoadMetadataCoroutineResult(callbackValue1, callbackValue2) else null) }) },
        mapDomainError = { error -> SecondaryClientNestedClientLoadMetadataException(error) },
        cancelOperation = { handle -> handle.cancel() },
    )


