// Generated by Gluecodium. Coroutine (suspend) support for @KotlinCoroutine functions.

package com.example.coroutines

import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlinx.coroutines.suspendCancellableCoroutine

/** Typed exception wrapper for LoadValueException, preserving the error value. */
public class LoadValueException(public val error: OperationError) : Exception(error.toString())

/** Typed exception wrapper for ClearCacheException, preserving the error value. */
public class ClearCacheException(public val error: OperationError) : Exception(error.toString())

/** Typed exception wrapper for LoadMetadataException, preserving the error value. */
public class LoadMetadataException(public val error: OperationError) : Exception(error.toString())

/** Typed exception wrapper for DownloadException, preserving the error value. */
public class DownloadException(public val error: OperationError) : Exception(error.toString())

/** Typed exception wrapper for TransferException, preserving the error value. */
public class TransferException(public val error: OperationError) : Exception(error.toString())

/** Thrown when the underlying SDK callback breaks its (error XOR result) contract. */
internal class SdkContractViolationException(message: String) : IllegalStateException(message)

/**
 * Generic bridge that adapts a callback-style [startOperation] into a `suspend` call returning [Result].
 *
 * Behavior:
 * - resumes with [Result.success] carrying the callback value,
 * - resumes with [Result.failure] produced by [mapDomainError] on a domain error,
 * - fails with [SdkContractViolationException] if the callback breaks the (error XOR result) contract,
 * - propagates a synchronous throwable from [startOperation],
 * - cancels the underlying task via [cancelOperation] when the coroutine is cancelled.
 */
internal suspend fun <E, T, H> awaitResultBridge(
    startOperation: (callback: (E?, T?) -> Unit) -> H,
    mapDomainError: (E) -> Throwable,
    cancelOperation: (H) -> Unit,
): Result<T> =
    suspendCancellableCoroutine { continuation ->
        val resolved = java.util.concurrent.atomic.AtomicBoolean(false)
        val handle: H? =
            try {
                startOperation { error, value ->
                    if (resolved.compareAndSet(false, true)) {
                        continuation.resume(
                            when {
                                error == null && value != null -> Result.success(value)
                                error != null && value == null -> Result.failure(mapDomainError(error))
                                error == null && value == null ->
                                    Result.failure(SdkContractViolationException("SDK contract violation: both error and value are null"))
                                else ->
                                    Result.failure(SdkContractViolationException("SDK contract violation: both error and value are non-null"))
                            }
                        )
                    }
                }
            } catch (throwable: Throwable) {
                if (resolved.compareAndSet(false, true)) {
                    continuation.resume(Result.failure(throwable))
                }
                null
            }
        if (handle != null) {
            continuation.invokeOnCancellation { cancelOperation(handle) }
        }
    }

/** Adapts a callback without a domain-error channel into a direct suspending value. */
internal suspend fun <T, H> awaitValueBridge(
    startOperation: (callback: (T) -> Unit) -> H,
    cancelOperation: (H) -> Unit,
): T =
    suspendCancellableCoroutine { continuation ->
        val resolved = java.util.concurrent.atomic.AtomicBoolean(false)
        val handle: H? =
            try {
                startOperation { value ->
                    if (resolved.compareAndSet(false, true)) {
                        continuation.resume(value)
                    }
                }
            } catch (throwable: Throwable) {
                if (resolved.compareAndSet(false, true)) {
                    continuation.resumeWithException(throwable)
                }
                null
            }
        if (handle != null) {
            continuation.invokeOnCancellation { cancelOperation(handle) }
        }
    }
