/*

 *
 */
// Generated by Gluecodium. Coroutine (suspend) support for @AsyncDecorator functions.

@file:JvmName("KotlinCoroutines_CoroutineClient_RemoteService_SecondaryClient_UploadSession")

package com.example.coroutines

import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlinx.coroutines.suspendCancellableCoroutine
import com.example.NativeBase

/**
 * Generic bridge that adapts a callback-style [startOperation] into a `suspend` call returning [Result].
 *
 * Behavior:
 * - resumes with [Result.success] carrying the callback value,
 * - resumes with [Result.failure] produced by [mapDomainError] on a domain error,
 * - fails with [IllegalStateException] if the callback breaks the (error XOR result) contract,
 * - propagates a synchronous throwable from [startOperation],
 * - cancels the underlying task via [cancelOperation] when the coroutine is cancelled before the
 *   callback resolves. The cancellation path shares the `resolved` guard with the callback, so a
 *   cancellation racing a completing callback never cancels an already-finished task.
 *
 * @param startOperation starts the underlying async operation and returns a handle.
 * @param mapDomainError converts the domain-specific error value into a [Throwable].
 * @param cancelOperation requests cancellation of the in-flight operation; the task may still
 *   complete on the native side.
 */
private suspend fun <E, T, H> awaitCoroutineResultBridge(
    startOperation: (callback: (E?, T?) -> Unit) -> H,
    mapDomainError: (E) -> Throwable,
    cancelOperation: (H) -> Unit,
): T =
    suspendCancellableCoroutine { continuation ->
        // Guards two races that `suspendCancellableCoroutine` does not cover on its own: a native callback
        // firing more than once, and `cancelOperation` running after the callback already resolved.
        val resolved = java.util.concurrent.atomic.AtomicBoolean(false)
        val handle: H? =
            try {
                startOperation { error, value ->
                    if (resolved.compareAndSet(false, true)) {
                        when {
                            error == null && value != null -> continuation.resume(value)
                            error != null && value == null -> continuation.resumeWithException(mapDomainError(error))
                            error == null && value == null ->
                                continuation.resumeWithException(IllegalStateException("Callback contract violation: both error and value are null"))
                            else ->
                                continuation.resumeWithException(IllegalStateException("Callback contract violation: both error and value are non-null"))
                        }
                    }
                }
            } catch (throwable: Throwable) {
                if (resolved.compareAndSet(false, true)) {
                    continuation.resumeWithException(throwable)
                }
                null
            }
        if (handle != null) {
            continuation.invokeOnCancellation {
                if (resolved.compareAndSet(false, true)) {
                    cancelOperation(handle)
                }
            }
        }
    }

/** Adapts a callback without a domain-error channel into a direct suspending value.
 *
 * @param startOperation starts the underlying async operation and returns a handle.
 * @param cancelOperation requests cancellation of the in-flight operation; the task may still
 *   complete on the native side.
 */
private suspend fun <T, H> awaitCoroutineValueBridge(
    startOperation: (callback: (T) -> Unit) -> H,
    cancelOperation: (H) -> Unit,
): T =
    suspendCancellableCoroutine { continuation ->
        // Guards two races that `suspendCancellableCoroutine` does not cover on its own: a native callback
        // firing more than once, and `cancelOperation` running after the callback already resolved.
        val resolved = java.util.concurrent.atomic.AtomicBoolean(false)
        val handle: H? =
            try {
                startOperation { value ->
                    if (resolved.compareAndSet(false, true)) {
                        continuation.resume(value)
                    }
                }
            } catch (throwable: Throwable) {
                if (resolved.compareAndSet(false, true)) {
                    continuation.resumeWithException(throwable)
                }
                null
            }
        if (handle != null) {
            continuation.invokeOnCancellation {
                if (resolved.compareAndSet(false, true)) {
                    cancelOperation(handle)
                }
            }
        }
    }

/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class RemoteServiceCheckConnectionException(public val error: OperationError) : Exception(error.toString())

/**
 * Coroutine (`suspend`) variant of `checkConnection`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 *
 * Checks whether the remote service is currently reachable.
 * @return when the operation completes.
 * @throws RemoteServiceCheckConnectionException on error.
 */
public suspend fun RemoteService.checkConnection(): Unit =
        awaitCoroutineResultBridge(
        startOperation = { callback -> this.checkConnection(ErrorOnlyCallback { error -> callback(error, if (error == null) Unit else null) }) },
        mapDomainError = { error -> RemoteServiceCheckConnectionException(error) },
        cancelOperation = { handle -> Unit },
    )


/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class UploadSessionUploadException(public val error: OperationError) : Exception(error.toString())

/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class UploadSessionOpenSessionException(public val error: OperationError) : Exception(error.toString())

/**
 * Coroutine (`suspend`) variant of `upload`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * @return the operation value.
 * @throws UploadSessionUploadException on error.
 */
public suspend fun UploadSession.upload(): String =
        awaitCoroutineResultBridge(
        startOperation = { callback -> this.upload(ErrorValueCallback { error, callbackValue1 -> callback(error, callbackValue1) }) },
        mapDomainError = { error -> UploadSessionUploadException(error) },
        cancelOperation = { handle -> Unit },
    )
/**
 * Coroutine (`suspend`) variant of `openSession`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * @return when the operation completes.
 * @throws UploadSessionOpenSessionException on error.
 */
public suspend fun UploadSession.Companion.openSession(): Unit =
        awaitCoroutineResultBridge(
        startOperation = { callback -> UploadSession.openSession(ErrorOnlyCallback { error -> callback(error, if (error == null) Unit else null) }) },
        mapDomainError = { error -> UploadSessionOpenSessionException(error) },
        cancelOperation = { handle -> Unit },
    )


/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class CoroutineClientLoadValueAsyncException(public val error: OperationError) : Exception(error.toString())

/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class CoroutineClientLoadWithOptionsException(public val error: OperationError) : Exception(error.toString())

/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class CoroutineClientPreloadException(public val error: OperationError) : Exception(error.toString())

/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class CoroutineClientRefreshException(public val error: OperationError) : Exception(error.toString())

/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class CoroutineClientClearCacheException(public val error: OperationError) : Exception(error.toString())

/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class CoroutineClientLoadMetadataException(public val error: OperationError) : Exception(error.toString())

/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class CoroutineClientListFeaturesException(public val error: OperationError) : Exception(error.toString())

/**
 * Coroutine (`suspend`) variant of `loadValue`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * Cancelling the coroutine requests cancellation of the underlying task; the task may still run to completion on the native side.
 * @return the operation value.
 * @throws CoroutineClientLoadValueAsyncException on error.
 */
public suspend fun CoroutineClient.loadValueAsync(): String =
        awaitCoroutineResultBridge(
        startOperation = { callback -> this.loadValue(ErrorValueCallback { error, callbackValue1 -> callback(error, callbackValue1) }) },
        mapDomainError = { error -> CoroutineClientLoadValueAsyncException(error) },
        cancelOperation = { handle -> handle.cancel() },
    )
/**
 * Coroutine (`suspend`) variant of `loadWithOptions`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * @param options
 * @return the operation value.
 * @throws CoroutineClientLoadWithOptionsException on error.
 */
public suspend fun CoroutineClient.loadWithOptions(options: RequestOptions = RequestOptions()): String =
        awaitCoroutineResultBridge(
        startOperation = { callback -> this.loadWithOptions(options, ErrorValueCallback { error, callbackValue1 -> callback(error, callbackValue1) }) },
        mapDomainError = { error -> CoroutineClientLoadWithOptionsException(error) },
        cancelOperation = { handle -> Unit },
    )
/**
 * Coroutine (`suspend`) variant of `preload`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * @return when the operation completes.
 * @throws CoroutineClientPreloadException on error.
 */
public suspend fun CoroutineClient.Companion.preload(): Unit =
        awaitCoroutineResultBridge(
        startOperation = { callback -> CoroutineClient.preload(ErrorOnlyCallback { error -> callback(error, if (error == null) Unit else null) }) },
        mapDomainError = { error -> CoroutineClientPreloadException(error) },
        cancelOperation = { handle -> Unit },
    )
/**
 * Coroutine (`suspend`) variant of `refresh`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * Cancelling the coroutine requests cancellation of the underlying task; the task may still run to completion on the native side.
 * @return when the operation completes.
 * @throws CoroutineClientRefreshException on error.
 */
public suspend fun CoroutineClient.refresh(): Unit =
        awaitCoroutineResultBridge(
        startOperation = { callback -> this.refresh(ErrorOnlyCallback { error -> callback(error, if (error == null) Unit else null) }) },
        mapDomainError = { error -> CoroutineClientRefreshException(error) },
        cancelOperation = { handle -> handle.abort() },
    )
/**
 * Coroutine (`suspend`) variant of `clearCache`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * @return when the operation completes.
 * @throws CoroutineClientClearCacheException on error.
 */
public suspend fun CoroutineClient.clearCache(): Unit =
        awaitCoroutineResultBridge(
        startOperation = { callback -> this.clearCache(ErrorOnlyCallback { error -> callback(error, if (error == null) Unit else null) }) },
        mapDomainError = { error -> CoroutineClientClearCacheException(error) },
        cancelOperation = { handle -> Unit },
    )
/**
 * Coroutine (`suspend`) variant of `resolveName`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 *
 * Resolves the display name for the current account.
 * @return the operation value.
 */
public suspend fun CoroutineClient.resolveName(): String? =
        awaitCoroutineValueBridge(
        startOperation = { callback -> this.resolveName(ValueOnlyCallback { callbackValue0 -> callback(callbackValue0) }) },
        cancelOperation = { handle -> Unit },
    )
/**
 * Coroutine (`suspend`) variant of `synchronize`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * @return when the operation completes.
 */
public suspend fun CoroutineClient.synchronize(): Unit =
        awaitCoroutineValueBridge(
        startOperation = { callback -> this.synchronize(CompletionCallback { callback(Unit) }) },
        cancelOperation = { handle -> Unit },
    )
/** Groups multiple result values returned by the `loadMetadata` coroutine wrapper. */
public data class CoroutineClientLoadMetadataCoroutineResult(
  public val count: Int,
  public val label: String
)

/**
 * Coroutine (`suspend`) variant of `loadMetadata`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * Cancelling the coroutine requests cancellation of the underlying task; the task may still run to completion on the native side.
 * @return the callback values grouped in a generated result type.
 * @throws CoroutineClientLoadMetadataException on error.
 */
public suspend fun CoroutineClient.loadMetadata(): CoroutineClientLoadMetadataCoroutineResult =
        awaitCoroutineResultBridge(
        startOperation = { callback -> this.loadMetadata(MultiValueCallback { error, callbackValue1, callbackValue2 -> callback(error, if (callbackValue1 != null && callbackValue2 != null) CoroutineClientLoadMetadataCoroutineResult(callbackValue1, callbackValue2) else null) }) },
        mapDomainError = { error -> CoroutineClientLoadMetadataException(error) },
        cancelOperation = { handle -> handle.cancel() },
    )
/**
 * Coroutine (`suspend`) variant of `listFeatures`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * @return the operation value.
 * @throws CoroutineClientListFeaturesException on error.
 */
public suspend fun CoroutineClient.listFeatures(): String =
        awaitCoroutineResultBridge(
        startOperation = { callback -> this.listFeatures(TrailingErrorCallback { callbackValue0, error -> callback(error, callbackValue0) }) },
        mapDomainError = { error -> CoroutineClientListFeaturesException(error) },
        cancelOperation = { handle -> Unit },
    )


/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class CoroutineClientNestedClientFetchNestedException(public val error: OperationError) : Exception(error.toString())

/**
 * Coroutine (`suspend`) variant of `fetchNested`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * Cancelling the coroutine requests cancellation of the underlying task; the task may still run to completion on the native side.
 * @return the operation value.
 * @throws CoroutineClientNestedClientFetchNestedException on error.
 */
public suspend fun CoroutineClient.NestedClient.fetchNested(): String =
        awaitCoroutineResultBridge(
        startOperation = { callback -> this.fetchNested(ErrorValueCallback { error, callbackValue1 -> callback(error, callbackValue1) }) },
        mapDomainError = { error -> CoroutineClientNestedClientFetchNestedException(error) },
        cancelOperation = { handle -> handle.cancel() },
    )


/**
 * Typed exception wrapper preserving the callback error value.
 *
 * @param error the domain-specific error returned by the callback.
 */
public class SecondaryClientNestedClientLoadMetadataException(public val error: OperationError) : Exception(error.toString())

/** Groups multiple result values returned by the `loadMetadata` coroutine wrapper. */
public data class SecondaryClientNestedClientLoadMetadataCoroutineResult(
  public val count: Int,
  public val label: String
)

/**
 * Coroutine (`suspend`) variant of `loadMetadata`.
 *
 * Suspends the calling coroutine until the operation completes instead of taking a callback.
 * Cancelling the coroutine requests cancellation of the underlying task; the task may still run to completion on the native side.
 * @return the callback values grouped in a generated result type.
 * @throws SecondaryClientNestedClientLoadMetadataException on error.
 */
public suspend fun SecondaryClient.NestedClient.loadMetadata(): SecondaryClientNestedClientLoadMetadataCoroutineResult =
        awaitCoroutineResultBridge(
        startOperation = { callback -> this.loadMetadata(MultiValueCallback { error, callbackValue1, callbackValue2 -> callback(error, if (callbackValue1 != null && callbackValue2 != null) SecondaryClientNestedClientLoadMetadataCoroutineResult(callbackValue1, callbackValue2) else null) }) },
        mapDomainError = { error -> SecondaryClientNestedClientLoadMetadataException(error) },
        cancelOperation = { handle -> handle.cancel() },
    )


