disabled_rules:
  - todo
  - nesting
excluded:
  - .build
  - build-ios
reporter: "junit"

type_name:
  max_length: 50
identifier_name: # index variable name is one letter by convention
  excluded:
    - i
type_body_length: # test cases tend to be longer
  - 500