#!/bin/bash
#
# Script to build the "hello" library for an iOS consumer. This is demonstrated
# by the platforms/swift application.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"

if [ "$1" == "--publish" ]; then
    publish_local
fi

TRANSPILER_VERSION="${TRANSPILER_VERSION:-+}"
BUILD_DIR=${PWD}/build-swift
INSTALL_DIR=${PWD}/dist/swift

[ -d "${BUILD_DIR}" ] || mkdir -p "${BUILD_DIR}"
[ -d "${INSTALL_DIR}" ] || mkdir -p "${INSTALL_DIR}"

CMAKE_EXTRA_PARAMETERS=
# Chose platform-native CMake generator
if [ "$(cmake_generator)" ] ; then
CMAKE_EXTRA_PARAMETERS="${CMAKE_EXTRA_PARAMETERS} \
    -G $(cmake_generator)"
fi

CWD=${PWD}
pushd "${BUILD_DIR}"
safe cmake \
    -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DHELLO_APIGEN_TRANSPILER_GENERATOR=swift \
    -DHELLO_APIGEN_TRANSPILER_VERSION="${TRANSPILER_VERSION}" \
    -DHELLO_SWIFT_TESTS="${CWD}/platforms/ios/Tests" \
    "${CMAKE_EXTRA_PARAMETERS}" \
    ..
popd

safe cmake \
    --build "${BUILD_DIR}" \
    --target install

exec "${INSTALL_DIR}/testhello"
