#!/bin/bash
#
# Script to build the "hello" library for an iOS consumer. This is demonstrated
# by the apps/swift application.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"

BUILD_DIR=build-ios
CWD=$PWD

if [ ! -d ${BUILD_DIR} ] ; then
    mkdir -p ${BUILD_DIR}
    cd ${BUILD_DIR}
    safe cmake \
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_TOOLCHAIN_FILE="${SCRIPT_DIR}/../../../apigen-cmake/cmake/toolchains/iOS.cmake" \
        -DCMAKE_INSTALL_PREFIX="$CWD/dist" \
        -DHELLO_APIGEN_TRANSPILER_GENERATOR=swift \
        -DHELLO_BUILD_CPP_APP=OFF \
        -G Ninja \
        ..
    cd ${CWD}
fi

safe cmake --build ${BUILD_DIR}
