#!/bin/bash
#
# Script to build the "hello" library for an iOS consumer. This is demonstrated
# by the apps/swift application.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"

BUILD_DIR=build-swift
CWD=${PWD}

if [ ! -d ${BUILD_DIR} ] ; then
    mkdir -p ${BUILD_DIR}
    safe cd ${BUILD_DIR}
    safe cmake \
        -DCMAKE_INSTALL_PREFIX="${CWD}"/dist \
        -DHELLO_APIGEN_TRANSPILER_GENERATOR=swift \
        -DHELLO_BUILD_CPP_APP=OFF \
        ..
    safe cd "${CWD}"
fi

safe cmake --build ${BUILD_DIR}