#!/bin/bash
#
# Script to build the "hello" library for an Android consumer. This is
# demonstrated by the apps/android application which is build externally.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"

# Build shared libraries
for arch in x86 armeabi-v7a ; do
    build_dir=build-android-${arch}
    if [ ! -d ${build_dir} ] ; then
        safe mkdir -p ${build_dir}
    fi

    pushd ${build_dir}
    safe cmake \
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_INSTALL_PREFIX=$CWD/dist \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_SYSTEM_VERSION=21 \
        -DCMAKE_ANDROID_ARCH_ABI=${arch} \
        -DCMAKE_ANDROID_NDK=$NDK_ROOT \
        -DCMAKE_ANDROID_STL_TYPE=gnustl_static \
        -DHELLO_APIGEN_TRANSPILER_GENERATOR=android \
        -DHELLO_BUILD_CPP_APP=OFF \
        -DHELLO_BUILD_IOS_APP=OFF \
        -G Ninja \
        ..
    popd
    safe cmake \
        --build ${build_dir}
done
