#!/bin/bash
#
# Script to build the entire project with some defaults.
#
# Note:
#  At the moment this only does a plain host build suitable for
#  stub and apps/base_api. Later on this might get expanded to
#  allow for other build types (e.g. which would disable apps/base_api
#  and use a different toolchain)

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"

BUILD_DIR=build
CWD=$PWD

if [ ! -d ${BUILD_DIR} ] ; then
    mkdir -p ${BUILD_DIR}
    cd ${BUILD_DIR}
    cmake \
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_INSTALL_PREFIX=$CWD/dist \
        -G Ninja \
        ..
    cd ${CWD}
fi

safe cmake --build ${BUILD_DIR}
