#!/bin/bash
#
# Script to build the "hello" library for a C++ consumer. This is demonstrated
# by the base_api application.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"

BUILD_DIR=${PWD}/build-cpp
INSTALL_DIR=${PWD}/dist/cpp

[ -d ${BUILD_DIR} ] || mkdir -p ${BUILD_DIR}
[ -d ${INSTALL_DIR} ] || mkdir -p ${INSTALL_DIR}

pushd ${BUILD_DIR}
safe cmake \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DHELLO_APIGEN_TRANSPILER_GENERATOR=stub \
    -DHELLO_BUILD_IOS_APP=OFF \
    -G Ninja \
    ..
popd

safe cmake \
    --build ${BUILD_DIR} \
    --target install
