#!/bin/bash
#
# Copyright (C) 2016-2019 HERE Europe B.V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE


# Script to create a new version commit
#
# Semantic Versioning: MAJOR.MINOR.PATCH

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
. "${SCRIPT_DIR}/inc.constants"
. "${SCRIPT_DIR}/inc.functions"

# Compare given old and new versions
#
# Usage: is_newer_than $old_version $new_version
#
# Return 0 if new_version is newer than old_version, 1 otherwise
function is_newer_than() {
    local old="$1"
    local new="$2"
    local newer=$(echo -e "$old\n$new" | sort --version-sort | tail -n1)

    if [ "$new" = "$newer" -a "$old" != "$newer" ]; then
        return 0
    fi
    return 1
}

OLD_VERSION=$(get_version "${GENIUM_VERSION_FILE}")

if [ $# -ne 1 ] ; then
    die "Usage: $0 MAJOR.MINOR.PATCH\n\n\tExample: $0 0.0.1\n\nCurrent version is ${OLD_VERSION}"
fi

# Increase SDK version (used as versionName in most modules)
NEW_VERSION=$1

if ! is_newer_than "$OLD_VERSION" "$NEW_VERSION"; then
    die "Error: We are already at version $OLD_VERSION"
fi

sed -i -e "s|version = $OLD_VERSION|version = $NEW_VERSION|" "${GENIUM_VERSION_FILE}"

# Create a commit with appropriate git tag
git commit \
    "${GENIUM_VERSION_FILE}" \
    -m "Release version $NEW_VERSION"
