#!/bin/bash -e
#
# Copyright (C) 2016-2018 HERE Europe B.V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE


# Git pre-commit hook that runs Google Java Format

# Run formatter only if any of the following file extensions have been staged to commit
# These file extensions are the same that are formatted with Spotless
if git diff --name-only --cached | egrep --quiet ".*\.(java|h|cpp|gradle|md|gitignore)$"; then
    echo "Formatting your repository..."

    # Go to project root directory
    cd $(git rev-parse --show-toplevel)

    # Run Google Java Format using Spotless
    ./gradlew spotlessApply --daemon >/dev/null 2>&1

    # Add formatted files again to commit (only those that were staged)
    git update-index --again

    echo "Formatting done."
fi
