#!/bin/bash
#
# Copyright (C) 2016-2018 HERE Europe B.V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE


# Script to build the "hello" library for a C++ consumer. This is demonstrated
# by the base_api application.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"

if [ "$1" == "--publish" ]; then
    publish_local
fi

GENIUM_VERSION="${GENIUM_VERSION:-+}"
BUILD_DIR=${PWD}/build-cpp
INSTALL_DIR=${PWD}/dist/cpp

[ -d ${BUILD_DIR} ] || mkdir -p ${BUILD_DIR}
[ -d ${INSTALL_DIR} ] || mkdir -p ${INSTALL_DIR}

CMAKE_EXTRA_PARAMETERS=
# Chose platform-native CMake generator
if [ "$(cmake_generator)" ] ; then
CMAKE_EXTRA_PARAMETERS="${CMAKE_EXTRA_PARAMETERS} \
    -G $(cmake_generator)"
fi

set -o pipefail

pushd ${BUILD_DIR}
safe cmake \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DHELLO_APIGEN_GENIUM_GENERATOR=cpp \
    -DHELLO_APIGEN_GENIUM_VERSION=${GENIUM_VERSION} \
    -DHELLO_BUILD_CPP_APP=ON \
    ${CMAKE_EXTRA_PARAMETERS} \
    .. | tee cmake_output.log
popd

safe cmake \
    --build ${BUILD_DIR} \
    --target install
