#!/bin/bash
#
# Copyright (C) 2016-2018 HERE Europe B.V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE

#
# Utility to format source code.
#
# Uses 'clang-format' and 'cmakelint' from containers with fixed versions
# to ensure consistency across machines. However, spotless is invoked directly
# via Gradle as versions are handled properly in this build-system. If the
# Android SDK is missing on the host, it uses a container as well. Lastly
# run SwiftLint on Swift sources as well.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"

# Format C++ with dockerized 'clang-format'
cpp_files=$(find . \( -name "*.h" -o -name "*.inl" -o -name "*.cpp" \) -exec echo /opt/{} \;)
safe docker run \
    --rm \
    --security-opt label=disable \
    --volume "${PWD}:/opt" \
    saschpe/clang-format -i ${cpp_files}

# Format CMake files with dockerized 'cmakelint'
cmake_files=$(find . \( -name CMakeLists.txt -o -name "*.cmake" \) -exec echo /opt/{} \;)
docker run \
    --rm \
    --security-opt label=disable \
    --volume "${PWD}:/opt" \
    saschpe/cmakelint --filter=-linelength ${cmake_files}

# Format Groovy, Java, Markdown and Kotlin via *spotless* Gradle plugin
if [ -d "${ANDROID_SDK_ROOT}" -o -d "${ANDROID_HOME}" ] ; then
    safe ./gradlew spotlessApply
else
  # If the Android SDK isn't available on the host, use a container.
  # We have to move 'local.properties' out of the way as it would confuse
  # the Android gradle plugin to look into wrong paths (as they differ in the
  # container).
  mv local.properties away 2>/dev/null
  safe docker run \
      --rm \
      --security-opt label=disable \
      --volume "${PWD}:/opt/project" \
      --workdir /opt/project \
      saschpe/android-sdk ./gradlew spotlessApply
  mv away local.properties 2>/dev/null
fi

# Format Swift files
pushd swift
    if command -v swiftlint  >/dev/null ; then
        echo "Formatting Swift files with 'swiftlint'..."
        safe swiftlint autocorrect
    else
        echo "Formatting Swift files with dockerized 'swiftlint'..."
        safe docker run \
            --rm \
            --security-opt label=disable \
            --volume ${PWD}:/opt \
            --workdir /opt \
            saschpe/swiftlint autocorrect
    fi
popd
