// Auto-generated by Gluecodium. Do not modify.

#include "NativeBasicModuleModule.h"
#include "FfiHandleRegistry.h"
#include "FfiLambdaProxy.h"
#include "FfiCallbackInit.h"
#include "FfiCallbackSlot.h"
#include "FfiOpaqueHandle.h"
#include <react/bridging/CallbackWrapper.h>

// FFI function declarations — resolved at link time from the pre-built SDK binary
extern "C" {
    FfiOpaqueHandle library_smoke_BasicModule_greet__String(FfiOpaqueHandle _self, int32_t _isolate_id, FfiOpaqueHandle name);
    FfiOpaqueHandle library_std_string_create_handle(const char* value);
    const char* library_std_string_get_value(FfiOpaqueHandle handle);
    double library_smoke_BasicModule_add__Double_Double(FfiOpaqueHandle _self, int32_t _isolate_id, double a, double b);
    void library_smoke_BasicModule_release_handle(FfiOpaqueHandle handle);
    void library_std_string_release_handle(FfiOpaqueHandle handle);
}

namespace facebook::react {

NativeBasicModuleModule::NativeBasicModuleModule(
    std::shared_ptr<CallInvoker> jsInvoker)
    : NativeBasicModuleModuleCxxSpec<NativeBasicModuleModule>(std::move(jsInvoker)) {}

void NativeBasicModuleModule::release(
    jsi::Runtime& rt, jsi::String __nativeHandle) {
  auto __handleStr = __nativeHandle.utf8(rt);
  FfiOpaqueHandle __handle = FfiHandleRegistry::instance().remove(__handleStr);
  if (__handle) {
    library_smoke_BasicModule_release_handle(__handle);
  }
}

jsi::String NativeBasicModuleModule::greet(
    jsi::Runtime& rt, jsi::String __nativeHandle, jsi::String name) {
  auto __handleStr = __nativeHandle.utf8(rt);
  FfiOpaqueHandle __self = FfiHandleRegistry::instance().retrieve(__handleStr);
  if (!__self) throw jsi::JSError(rt, "Invalid native handle");
  auto __str_name = name.utf8(rt);
  FfiOpaqueHandle __ffi_name_0 = library_std_string_create_handle(__str_name.c_str());
  auto __ffiResult = library_smoke_BasicModule_greet__String(__self, 0, __ffi_name_0);
  library_std_string_release_handle(__ffi_name_0);
  if (!__ffiResult) throw jsi::JSError(rt, "FFI returned null string handle");
  auto __strVal = library_std_string_get_value(__ffiResult);
  auto __jsiStr = jsi::String::createFromUtf8(rt, __strVal);
  library_std_string_release_handle(__ffiResult);
  return __jsiStr;
}

double NativeBasicModuleModule::add(
    jsi::Runtime& rt, jsi::String __nativeHandle, double a, double b) {
  auto __handleStr = __nativeHandle.utf8(rt);
  FfiOpaqueHandle __self = FfiHandleRegistry::instance().retrieve(__handleStr);
  if (!__self) throw jsi::JSError(rt, "Invalid native handle");
  auto __ffiResult = library_smoke_BasicModule_add__Double_Double(__self, 0, a, b);
  return __ffiResult;
}

} // namespace facebook::react
