// Auto-generated by Gluecodium. Do not modify.

#pragma once

#include <AppSpecsJSI.h>
#include <memory>
#include <string>

namespace facebook::react {

class NativeBasicModuleModule
    : public NativeBasicModuleModuleCxxSpec<NativeBasicModuleModule> {
public:
  explicit NativeBasicModuleModule(std::shared_ptr<CallInvoker> jsInvoker);

  void release(jsi::Runtime& rt, jsi::String __nativeHandle);
  jsi::String greet(jsi::Runtime& rt, jsi::String __nativeHandle, jsi::String name);
  double add(jsi::Runtime& rt, jsi::String __nativeHandle, double a, double b);
};

} // namespace facebook::react
