name: Unit tests

on: [push, pull_request]

jobs:
  build:
    name: Build and unit tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            !*gluecodium*
            !*lime-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and test :lime-runtime
        run: ./gradlew :lime-runtime:build
      - name: Build and test :lime-loader
        run: ./gradlew :lime-loader:build
      - name: Build and test :gluecodium
        run: ./gradlew :gluecodium:build
      - name: Build and test :gluecodium-gradle
        run: ./gradlew :gluecodium-gradle:build
